---
title: "LHD Assignments"
author: "Kenny Quintana"
format: html
editor: visual
---

## Adele

Make a copy of 'Low Head Dam Info.xlsx' and prepare it to be read by python by

1.  removing locations that are not dams (blacked out)
2.  making sure all numbers are readable (no characters in the cell)

## Eliana

Work on a program to download specific stream lines using StreamID from a .gpkg found [here](http://geoglows-v2.s3-website-us-west-2.amazonaws.com/#streams/). You can also work on finding which .gpkg to download based on StreamID.

```{python Eliana}

```

## Paige

Work on a program to read the lat long from the .xlsx, create a new column with Hydroviewer URLs. Then you can click on all the URLs, make sure they have low-head dams, and add the StreamID to a new StreamID column.

```{python Paige}
#| echo: true

# this is the format for the URL
def hydroviewer_url(lat, lon):
  return f"https://hydroviewer.geoglows.org/#lon={lon}&lat={lat}&zoom=14.56&definition="

# example
lat = 1
lon = 1
hydroviewer_url(lat, lon)

```

## Sarah

Work on a program to download retrospective data from GEOGLOWS using a StreamID. Once you have the data, create a flow duration curve and return the 50% exceedance probability flow. There are tutorials [here](https://training.geoglows.org/data-catalog/).
